export const ACTIVATION_BEGIN = 'ACTIVATION_BEGIN';
export const ACTIVATION_CLEAR = 'ACTIVATION_CLEAR';
export const ACTIVATION_FAILURE = 'ACTIVATION_FAILURE';
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const LOGIN_BEGIN = 'LOGIN_BEGIN';
export const LOGIN_CLEAR = 'LOGIN_CLEAR';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const PASSWORD_EMAIL_BEGIN = 'PASSWORD_EMAIL_BEGIN';
export const PASSWORD_EMAIL_CLEAR = 'PASSWORD_EMAIL_CLEAR';
export const PASSWORD_EMAIL_FAILURE = 'PASSWORD_EMAIL_FAILURE';
export const PASSWORD_EMAIL_SUCCESS = 'PASSWORD_EMAIL_SUCCESS';
export const PASSWORD_RESET_BEGIN = 'PASSWORD_RESET_BEGIN';
export const PASSWORD_RESET_CLEAR = 'PASSWORD_RESET_CLEAR';
export const PASSWORD_RESET_FAILURE = 'PASSWORD_RESET_FAILURE';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const REGISTRATION_BEGIN = 'REGISTRATION_BEGIN';
export const REGISTRATION_CLEAR = 'REGISTRATION_CLEAR';
export const REGISTRATION_FAILURE = 'REGISTRATION_FAILURE';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const SET_TOKEN = 'SET_TOKEN';
export const REMOVE_TOKEN = 'REMOVE_TOKEN';
export const SET_SERVER_TIME = 'SET_SERVER_TIME';
export const USERS_SEARCH_BEGIN = 'USERS_SEARCH_BEGIN';
export const USERS_SEARCH_SUCCESS = 'USERS_SEARCH_SUCCESS';
export const USERS_SEARCH_FAILURE = 'USERS_SEARCH_FAILURE';

export const SET_REFRESH_TOKEN = 'SET_REFRESH_TOKEN';
export const REMOVE_REFRESH_TOKEN = 'REMOVE_REFRESH_TOKEN';
export const REFRESH_TOKEN_BEGIN = 'REFRESH_TOKEN_BEGIN';
export const REFRESH_TOKEN_FAILURE = 'REFRESH_TOKEN__FAILURE';
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN__SUCCESS';

export const EMOTION_CODE_LIST = 'EMOTION_CODE_LIST';
export const FILTER_CODE_LIST = 'FILTER_CODE_LIST';
export const COMMON_CODE_LIST = 'COMMON_CODE_LIST';
export const SELECTED_EMOTION_CODE = 'SELECTED_EMOTION_CODE';
export const SELECTED_FILTER_CODE = 'SELECTED_FILTER_CODE';
export const SELECTED_COMMON_CODE = 'SELECTED_COMMON_CODE';
export const SPEECH_CODE_LIST = 'SPEECH_CODE_LIST';
export const SELECTED_SPEECH_CODE = 'SELECTED_SPEECH_CODE';

export const LUIS_SELECT_APP = 'LUIS_SELECT_APP';
export const LUIS_SELECT_APP_ID = 'LUIS_SELECT_APP_ID';
export const LUIS_API_KEY = 'LUIS_API_KEY';
export const LUIS_SELECT_APP_INTENT_LIST = 'LUIS_SELECT_APP_INTENT_LIST';
export const LUIS_SELECT_APP_ENTITY_LIST = 'LUIS_SELECT_APP_ENTITY_LIST';
export const LUIS_SELECT_APP_MODEL_LIST = 'LUIS_SELECT_APP_MODEL_LIST';
export const LUIS_INIT_STATUS = 'LUIS_INIT_STATUS';

export const LUIS_INIT_STATUS_INIT = 'LUIS_INIT_STATUS_INIT';
export const LUIS_INIT_STATUS_CALL = 'LUIS_INIT_STATUS_CALL';
export const LUIS_INIT_STATUS_UPDATE = 'LUIS_INIT_STATUS_UPDATE';

export const LOADING_STATE = 'LOADING_STATE';

export const SPEECH_CONTENT_LIST = 'SPEECH_CONTENT_LIST';
export const SELECTED_SPEECH_CONTENT_LIST = 'SELECTED_SPEECH_CONTENT_LIST';

export const EMOTION_SPEECH_MAPPING_LIST = 'EMOTION_SPEECH_MAPPING_LIST';
export const SELECTED_EMOTION_SPEECH_MAPPING_LIST = 'SELECTED_EMOTION_SPEECH_MAPPING_LIST';

// SITE
export const SITE_MENU_LIST = 'SITE_MENU_LIST';
export const SITE_SUB_MENU_LIST = 'SITE_SUB_MENU_LIST';
// API LIST
